# Generated by Django 4.2 on 2023-04-25 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ordens_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField(max_length=255)),
                ('email', models.TextField(max_length=255)),
                ('contato', models.FloatField()),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('modelo', models.TextField(max_length=10)),
                ('marca', models.TextField(max_length=10)),
                ('avarias', models.BooleanField(default=False)),
                ('cartao_memoria', models.BooleanField(default=False)),
                ('chip', models.BooleanField(default=False)),
                ('tampa', models.BooleanField(default=False)),
                ('capa', models.BooleanField(default=False)),
                ('tela', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=False)),
                ('touch', models.BooleanField(default=False)),
                ('ligando', models.BooleanField(default=False)),
                ('vibrando', models.BooleanField(default=False)),
                ('oxidacao', models.BooleanField(default=False)),
                ('botao_home', models.BooleanField(default=False)),
                ('botao_power', models.BooleanField(default=False)),
                ('botoes_volume', models.BooleanField(default=False)),
                ('conector_carga', models.BooleanField(default=False)),
                ('slot_chip', models.BooleanField(default=False)),
                ('outros', models.BooleanField(default=False)),
                ('bateria', models.BooleanField(default=False)),
                ('senha', models.BooleanField(default=False)),
                ('defeito', models.TextField(max_length=50)),
            ],
        ),
    ]
