# Generated by Django 4.2 on 2023-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0002_listadeprecos'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadeprecos',
            name='marca',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listadeprecos',
            name='modelo',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listadeprecos',
            name='pecaeservico',
            field=models.TextField(max_length=50),
        ),
    ]
